fix: add system-observe to plugs #2

diff --git a/utilities/installers/linux/snapbuild b/utilities/installers/linux/snapbuild
--- a/utilities/installers/linux/snapbuild
+++ b/utilities/installers/linux/snapbuild
@@ -1,6 +1,12 @@
 #! /bin/bash
 set -eo pipefail
 
+
+if ! which flutter > /dev/null; then
+  echo "Flutter not found. Please install Flutter before running this script." >&2
+  exit 1
+fi
+
 # required to upgrade ubuntu base due to incompatible libraries
 echo "Updating dependencies..."
 
@@ -32,22 +38,15 @@ sed -i "s/^version:.*$/version: $VERSION/g" snapcraft.yaml
 if [ -d local ]; then rm -rf local; fi
 mkdir local
 
-openssl aes-256-cbc -d \
-  -in snap_credentials.enc \
-  -out local/snapcraft.login \
-  -k "$SNAPCRAFT_CREDENTIALS_KEY"
+#openssl aes-256-cbc -d \
+#  -in snap_credentials.enc \
+#  -out local/snapcraft.login \
+#  -k "$SNAPCRAFT_CREDENTIALS_KEY"
+echo "$SNAPCRAFT_LOGIN_FILE" | base64 --decode --ignore-garbage > local/snapcraft.login
 
 snapcraft login --with local/snapcraft.login
 
 cd .. || exit 0
-
-if ! which flutter > /dev/null; then
-    echo ""
-    echo "Flutter not found, installing..."
-    FL_PATH=$(bash <(curl -s https://raw.githubusercontent.com/brenodt/flutter_utilities/main/bin/flinstall) "3.3.1")
-    export PATH="${FL_PATH}:${PATH}"
-    flutter pub get
-fi
 
 echo ""
 echo "Building Flutter application..."
