chore: [Flutter] MacOS - add code-signing to the installer script

diff --git a/utilities/installers/macos/bin/dmgbuild b/utilities/installers/macos/bin/dmgbuild
--- a/utilities/installers/macos/bin/dmgbuild
+++ b/utilities/installers/macos/bin/dmgbuild
@@ -12,8 +12,8 @@ echo "Retrieving application version..."
 cd ../../../../qaul_ui || exit 1
 
 if [ ! -f pubspec.yaml ]; then
-    echo "pubspec.yaml not found!"
-    exit 1
+  echo "pubspec.yaml not found!"
+  exit 1
 fi
 
 VERSION=$(grep "version:" pubspec.yaml | awk '{ print $2}')
@@ -26,4 +26,17 @@ echo "Updating app version on config.json..."
 
 sed -i sed "s/\"title\": \".*\"/\"title\": \"qaul-$VERSION\"/g" config.json
 
-appdmg ./config.json "qaul-$VERSION.dmg"
+echo ""
+echo "Updating the signing identity on config.json..."
+
+# Get list of certificates available locally, filtering out revoked ones.
+SIGNING_IDENTITY=$(
+  security find-identity -v -p codesigning |
+    grep --invert-match "(CSSMERR_TP_CERT_REVOKED)" |
+    grep "Apple Distribution: Verein zur Forderung von offenen Community-Projekten" |
+    awk '{ print $2 }' |
+    head -n1 \
+)
+sed -i sed "s/\"signing-identity\": \".*\"/\"signing-identity\": \"$SIGNING_IDENTITY\"/g" config.json
+
+npx appdmg ./config.json "qaul-$VERSION.dmg"
