feat: update linux snap build job

diff --git a/qaul_ui/installers/linux/snapbuild b/qaul_ui/installers/linux/snapbuild
--- a/qaul_ui/installers/linux/snapbuild
+++ b/qaul_ui/installers/linux/snapbuild
@@ -1,20 +1,55 @@
 #! /bin/bash
 
 # required to upgrade ubuntu base due to incompatible libraries
+echo "Updating dependencies..."
+
 sed -i "s/xenial/focal/g" /etc/apt/sources.list
 apt update -qq
 apt install -y -qq wget tar unzip zip lib32stdc++6 lib32z1 git clang cmake ninja-build pkg-config libgtk-3-dev curl
 
+echo ""
+
 flutter config --enable-linux-desktop
 
-cd ../../snap || exit
+echo ""
+echo "Retrieving application version..."
+
+cd ../..
+
+if [ ! -f pubspec.yaml ]; then
+    echo "pubspec.yaml not found!"
+    exit 1
+fi
+
+VERSION=$(grep "version:" pubspec.yaml | awk '{ print $2}')
+echo "Using App Version: $VERSION"
+
+cd snap || exit
+
+echo ""
+echo "Updating app version on snapcraft.yaml and logging into snapcraft..."
 
 # ignore current snap version and set to pubspec version
 # "s/version\:\W\+[0-9]\+\.[0-9]\+\.[0-9]\+/version: $VERSION/g" or "s/[0-9]\+\.[0-9]\+\.[0-9]\+/$VERSION/g"
 sed -i "s/version\:\W\+[0-9]\+\.[0-9]\+\.[0-9]\+/version: $VERSION/g" snapcraft.yaml
-echo "$SNAPCRAFT_LOGIN_FILE" | base64 --decode --ignore-garbage > snapcraft.login
-snapcraft login --with snapcraft.login
+
+mkdir local
+echo "$SNAPCRAFT_LOGIN_FILE" | base64 --decode --ignore-garbage > local/snapcraft.login
+snapcraft login --with local/snapcraft.login
 set +o pipefail
+
+# shellcheck disable=SC2103
+cd ..
+
+echo ""
+echo "Building Flutter application..."
+
+git config --global --add safe.directory /root/development/flutter
+
 snapcraft
 mv ./*.snap "qaul-app-$VERSION.snap"
-snapcraft upload "qaul-app-$VERSION.snap" --release=stable
+# TODO cannot upload via CircleCI due to the directive:
+#     - human review required due to 'deny-connection' constraint (interface attributes)
+# snapcraft upload "qaul-app-$VERSION.snap" --release=stable
+
+realpath "qaul-app-$VERSION.snap"
