ci: clean config file and add build-libqaul-android as a requirement to android-beta-deploy

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,7 +1,7 @@
 version: 2.1
 
 # ------------------------------------------------
-# Configuration anchors
+# Configurations
 # ------------------------------------------------
 flutter_version: &flutter_version
   FLUTTER_VERSION: "2.8.0"
@@ -68,7 +68,7 @@ jobs:
   # #  ---------------------------------------------
   # #  Rust
   # #  ---------------------------------------------
-  build-libaqul-android:
+  build-libqaul-android:
     executor: android-rust
     working_directory: ~/qaul-libp2p
     shell: /bin/bash --login -o pipefail
@@ -108,24 +108,6 @@ jobs:
           paths:
             - android/blemodule/build/outputs/aar/blemodule-debug.aar
             - android/libqaul/build/outputs/aar/libqaul-debug.aar
-  downstream:
-    executor: android-rust
-    working_directory: ~/qaul-libp2p
-    steps:
-      - restore_cache: *restore_git_cache
-      - checkout-project
-      - save_cache: *save_git_cache
-      - attach_workspace:
-          at: ~/qaul-libp2p
-      - run: ls -alt
-      - run: cd android/libqaul/build/outputs/aar && ls -alt
-      - run: cd android/blemodule/build/outputs/aar && ls -alt
-      - run: |
-          if [ ! -f android/libqaul/build/outputs/aar/libqaul-debug.aar ]; then
-            echo "Nope!";
-          else
-            echo "It worked!";
-          fi
   # #  ---------------------------------------------
   # #  Android
   # #  ---------------------------------------------
@@ -141,11 +123,17 @@ jobs:
       <<: *flutter_version
     shell: /bin/bash --login -o pipefail
     steps:
-      - attach_workspace:
-          at: ~/qaul-libp2p/android/libqaul/build/outputs/aar
       - restore_cache: *restore_git_cache
       - checkout-project
       - save_cache: *save_git_cache
+      - attach_workspace:
+          at: ~/qaul-libp2p
+      - run:
+          name: Check for presence of AAR Files
+          command: |
+            if [ [ ! -f android/libqaul/build/outputs/aar/libqaul-debug.aar ] || [ ! -f android/blemodule/build/outputs/aar/blemodule-debug.aar ] ]; then
+              echo "Libqaul/blemodule AAR file could not be found. That's probably due an error in persisting files to workspace"; exit 1
+            fi
       - install-flutter-linux:
           version: "$FLUTTER_VERSION"
       - install-flutter-deps
@@ -194,16 +182,14 @@ jobs:
           destination: output
 
 workflows:
-  build-test:
-    jobs:
-      - build-libaqul-android
-      - downstream:
-          requires:
-            - build-libaqul-android
   flutter-ci-cd-workflow:
     jobs:
       - flutter-analyze
       - flutter-test
+      - build-libqaul-android:
+          filters:
+            branches:
+              only: beta
       - hold:
           type: approval
           requires:
@@ -215,53 +201,26 @@ workflows:
       - android-beta-deploy:
           requires:
             - hold
+            - build-libqaul-android
           filters:
             branches:
               only: beta
-      - ios-beta-deploy:
-          requires:
-            - hold
-          filters:
-            branches:
-              only: beta
+#      - ios-beta-deploy:
+#          requires:
+#            - hold
+#          filters:
+#            branches:
+#              only: beta
 
 commands:
   checkout-project:
     description: "Invokes the checkout CircleCI step, declaring `path` as the root of the project (defined by `checkout_to_project_root` anchor)"
     <<: *checkout_to_root
 
-  install-flutter-linux:
-    description: "Installs the Linux flutter binary"
-    parameters:
-      version:
-        type: string
-    steps:
-      - run:
-          name: Install Flutter
-          command: |
-            cd && mkdir .flutter-sdk
-            cd .flutter-sdk
-            curl --fail --remote-time --silent --location -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_<< parameters.version >>-stable.tar.xz
-            tar xf flutter_linux_<< parameters.version >>-stable.tar.xz --strip-components=1
-            rm flutter_linux_<< parameters.version >>-stable.tar.xz
-            echo "export PATH=$PATH:`pwd`/bin" >> $BASH_ENV
 
-  install-flutter-macos:
-    description: "Installs the MacOS flutter binary"
-    parameters:
-      version:
-        type: string
-    steps:
-      - run:
-          name: Install Flutter
-          command: |
-            cd && mkdir .flutter-sdk
-            cd .flutter-sdk
-            curl --fail --remote-time --silent --location -O https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_<< parameters.version >>-stable.zip
-            unzip flutter_macos_<< parameters.version >>-stable.zip
-            rm flutter_macos_<< parameters.version >>-stable.zip
-            echo "export PATH=$PATH:`pwd`/flutter/bin" >> $BASH_ENV
-
+  # ------------------------------------------------
+  # Flutter-related commands
+  # ------------------------------------------------
   install-flutter-deps:
     description: "Install Flutter dependencies"
     parameters:
@@ -308,6 +267,46 @@ commands:
           paths:
             - vendor/bundle
 
+
+  # #  ---------------------------------------------
+  # #  (Flutter) Android-related commands
+  # #  ---------------------------------------------
+  install-flutter-linux:
+    description: "Installs the Linux flutter binary"
+    parameters:
+      version:
+        type: string
+    steps:
+      - run:
+          name: Install Flutter
+          command: |
+            cd && mkdir .flutter-sdk
+            cd .flutter-sdk
+            curl --fail --remote-time --silent --location -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_<< parameters.version >>-stable.tar.xz
+            tar xf flutter_linux_<< parameters.version >>-stable.tar.xz --strip-components=1
+            rm flutter_linux_<< parameters.version >>-stable.tar.xz
+            echo "export PATH=$PATH:`pwd`/bin" >> $BASH_ENV
+
+
+  # #  ---------------------------------------------
+  # #  (Flutter) iOS-related commands
+  # #  ---------------------------------------------
+  install-flutter-macos:
+    description: "Installs the MacOS flutter binary"
+    parameters:
+      version:
+        type: string
+    steps:
+      - run:
+          name: Install Flutter
+          command: |
+            cd && mkdir .flutter-sdk
+            cd .flutter-sdk
+            curl --fail --remote-time --silent --location -O https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_<< parameters.version >>-stable.zip
+            unzip flutter_macos_<< parameters.version >>-stable.zip
+            rm flutter_macos_<< parameters.version >>-stable.zip
+            echo "export PATH=$PATH:`pwd`/flutter/bin" >> $BASH_ENV
+
   install-cocoapods-deps:
     description: "Install Pods dependencies"
     steps:
@@ -322,6 +321,7 @@ commands:
           key: pods-cache-v1-{{ arch }}-{{ checksum "Podfile.lock" }}
           paths:
             - ./Pods
+
 
   # ------------------------------------------------
   # Rust-related commands
