ci: add flutter Windows build job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,5 +1,8 @@
 version: 2.1
 
+orbs:
+  win: circleci/windows@4.1
+
 # ------------------------------------------------
 # Configurations
 # ------------------------------------------------
@@ -66,9 +69,16 @@ jobs:
   # Deploy Jobs
   # ------------------------------------------------
   publish-github-release:
+    working_directory: ~/qaul-libp2p
     docker:
-      - image: cibuilds/github:0.13
+      - image: cimg/rust:1.60.0
+#      - image: cibuilds/github:0.13
+    environment:
+      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
     steps:
+      - restore_cache: *restore_git_cache
+      - checkout-project
+      - save_cache: *save_git_cache
       - attach_workspace:
           at: ~/qaul-libp2p
       - run:
@@ -86,10 +96,26 @@ jobs:
             cp rust/target/debug/liblibqaul.dylib ./artifacts/
             # MacOS
             cp rust/target/universal/release/liblibqaul.a ./artifacts/
+            # Windows
+            cp rust/target/debug/libqaul.dll ./artifacts/
+#      - run:
+#          name: Install Rust
+#          command: |
+#            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
+#            echo "export PATH=${HOME}/.cargo/bin:${PATH}" >> $BASH_ENV
+      - run:
+          name: Install ghr
+          command: |
+            GHR_VERSION=0.13.0
+            GHR_URL=https://github.com/tcnksm/ghr/releases/download/v${GHR_VERSION}/ghr_v${GHR_VERSION}_linux_amd64.tar.gz
+            wget "$GHR_URL"
+            tar xzf ghr_v${GHR_VERSION}_linux_amd64.tar.gz
+            rm -r ghr_v${GHR_VERSION}_linux_amd64.tar.gz
+            echo "export PATH=ghr_v${GHR_VERSION}_linux_amd64:${PATH}" >> $BASH_ENV
       - run:
           name: Publish Release on GitHub
           command: |
-            VERSION=$(cd rust/libqaul && cargo pkgid | cut -d# -f2 | cut -d: -f2)
+            VERSION=$(cd rust/libqaul && cargo generate-lockfile -q && cargo pkgid | cut -d# -f2 | cut -d: -f2)
             ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
   # #  ---------------------------------------------
   # #  Rust
@@ -111,7 +137,7 @@ jobs:
       - setup-sccache
       - restore-sccache-cache
       - run:
-          name: Build Libqaul JniLibs for Android
+          name: Build Libqaul for Linux
           command: cd rust && cargo build --release
       - save-sccache-cache
       - persist_to_workspace:
@@ -255,6 +281,43 @@ jobs:
           steps:
             - store_artifacts:
                 path: rust/target/debug/liblibqaul.dylib
+  # # #  -------------------------------------------
+  # # #  (Rust) Windows
+  # # #  -------------------------------------------
+  build-libqaul-windows:
+    executor:
+      name: win/default
+      size: "medium"
+      shell: bash.exe
+    working_directory: ~/qaul-libp2p
+    environment:
+      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
+    steps:
+      - restore_cache: *restore_git_cache
+      - checkout-project
+      - save_cache: *save_git_cache
+      - run:
+          name: Install CMake
+          shell: powershell.exe
+          command: choco install cmake -y
+      - run:
+          name: Install Rust
+          command: |
+            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
+            export PATH="/c/Users/circleci/.cargo/bin:$PATH"
+            cargo --version
+            rustup --version
+            rustc --version
+      - run:
+          name: Build dll Libqaul
+          no_output_timeout: 30m
+          command: |
+            export PATH="/c/Users/circleci/.cargo/bin:/c/Program Files/CMake/bin:$PATH"
+            cd rust && cargo build
+      - persist_to_workspace:
+          root: ~/qaul-libp2p
+          paths:
+            - rust/target/debug/libqaul.dll
   # #  ---------------------------------------------
   # #  Flutter
   # #  ---------------------------------------------
@@ -286,7 +349,7 @@ jobs:
             if [ ! -f ../../android/libqaul/build/outputs/aar/libqaul-debug.aar ] || [ ! -f ../../android/blemodule/build/outputs/aar/blemodule-debug.aar ]; then
               echo "Libqaul/blemodule AAR file could not be found. That's probably due an error in persisting files to workspace"; exit 1
             fi
-      - install-flutter-linux:
+      - install-flutter:
           version: "$FLUTTER_VERSION"
       - install-flutter-deps
       - run:
@@ -326,7 +389,7 @@ jobs:
             if [ ! -f ../../rust/target/universal/release/liblibqaul.a ]; then
               echo "Libqaul *.a file could not be found. That's probably due an error in persisting files to workspace"; exit 1
             fi
-      - install-flutter-macos:
+      - install-flutter:
           version: "$FLUTTER_VERSION"
       - install-flutter-deps
       - install-bundler-deps
@@ -340,6 +403,39 @@ jobs:
       - store_artifacts:
           path: output
           destination: output
+  # # #  -------------------------------------------
+  # # #  (Flutter) Windows
+  # # #  -------------------------------------------
+  windows-beta-deploy:
+    executor:
+      name: win/server-2022
+      size: "medium"
+      shell: bash.exe
+    working_directory: ~/qaul-libp2p/qaul_ui
+    environment:
+      <<: *flutter_version
+    shell: /bin/bash --login -o pipefail
+    steps:
+      - restore_cache: *restore_git_cache
+      - checkout-project
+      - save_cache: *save_git_cache
+      - attach_workspace:
+          at: ~/qaul-libp2p
+      - run:
+          name: Check for presence of *.dll Library
+          command: |
+            if [ ! -f ../../rust/target/debug/libqaul.dll ]; then
+              echo "Libqaul *.dll file could not be found. That's probably due an error in persisting files to workspace"; exit 1
+            fi
+      - install-flutter:
+          version: "$FLUTTER_VERSION"
+      - run:
+          name: Flutter Doctor
+          command: flutter doctor
+      - install-flutter-deps
+      - run:
+          name: Build Flutter Application for Windows
+          command: flutter build windows
 
 # ------------------------------------------------
 # Workflows
@@ -354,25 +450,25 @@ workflows:
       - flutter-test:
           filters:
             tags:
-              only: /^\d+\.\d+\.\d+-flutter$/
+              only: /^\d+\.\d+\.\d+(\+\d)*-flutter$/
             branches:
               ignore: /.*/
       - flutter-analyze:
           filters:
             tags:
-              only: /^\d+\.\d+\.\d+-flutter$/
+              only: /^\d+\.\d+\.\d+(\+\d)*-flutter$/
             branches:
               ignore: /.*/
       - build-libqaul-android:
           filters:
             tags:
-              only: /^\d+\.\d+\.\d+-flutter$/
+              only: /^\d+\.\d+\.\d+(\+\d)*-flutter$/
             branches:
               ignore: /.*/
       - build-libqaul-ios:
           filters:
             tags:
-              only: /^\d+\.\d+\.\d+-flutter$/
+              only: /^\d+\.\d+\.\d+(\+\d)*-flutter$/
             branches:
               ignore: /.*/
       - android-beta-deploy:
@@ -382,7 +478,7 @@ workflows:
             - build-libqaul-android
           filters:
             tags:
-              only: /^\d+\.\d+\.\d+-flutter$/
+              only: /^\d+\.\d+\.\d+(\+\d)*-flutter$/
             branches:
               ignore: /.*/
       - ios-beta-deploy:
@@ -392,47 +488,53 @@ workflows:
             - build-libqaul-ios
           filters:
             tags:
-              only: /^\d+\.\d+\.\d+-flutter$/
+              only: /^\d+\.\d+\.\d+(\+\d)*-flutter$/
             branches:
               ignore: /.*/
-
   rust-build-and-deploy:
     jobs:
-      - build-libqaul-linux:
-          filters:
-            tags:
-              only: /^\d+\.\d+\.\d+-rust$/
-            branches:
-              ignore: /.*/
-      - build-libqaul-android:
-          filters:
-            tags:
-              only: /^\d+\.\d+\.\d+-rust$/
-            branches:
-              ignore: /.*/
-      - build-libqaul-ios:
-          filters:
-            tags:
-              only: /^\d+\.\d+\.\d+-rust$/
-            branches:
-              ignore: /.*/
-      - build-libqaul-macos:
-          filters:
-            tags:
-              only: /^\d+\.\d+\.\d+-rust$/
-            branches:
-              ignore: /.*/
+      - build-libqaul-linux
+#          filters:
+#            tags:
+#              only: /^\d+\.\d+\.\d+(\+\d)*-rust$/
+#            branches:
+#              ignore: /.*/
+      - build-libqaul-android
+#          filters:
+#            tags:
+#              only: /^\d+\.\d+\.\d+(\+\d)*-rust$/
+#            branches:
+#              ignore: /.*/
+      - build-libqaul-ios
+#          filters:
+#            tags:
+#              only: /^\d+\.\d+\.\d+(\+\d)*-rust$/
+#            branches:
+#              ignore: /.*/
+      - build-libqaul-macos
+#          filters:
+#            tags:
+#              only: /^\d+\.\d+\.\d+(\+\d)*-rust$/
+#            branches:
+#              ignore: /.*/
+      - build-libqaul-windows
+#          filters:
+#            tags:
+#              only: /^\d+\.\d+\.\d+(\+\d)*-rust$/
+#            branches:
+#              ignore: /.*/
       - publish-github-release:
           requires:
             - build-libqaul-linux
             - build-libqaul-android
             - build-libqaul-ios
             - build-libqaul-macos
-          filters:
-            tags:
-              only: /^\d+\.\d+\.\d+-rust$/
-            branches:
-              ignore: /.*/
+            - build-libqaul-windows
+#          filters:
+#            tags:
+#              only: /^\d+\.\d+\.\d+(\+\d)*-rust$/
+#            branches:
+#              ignore: /.*/
 
 # ------------------------------------------------
 # Reusable commands
@@ -446,6 +548,17 @@ commands:
   # ------------------------------------------------
   # Flutter-related commands
   # ------------------------------------------------
+  install-flutter:
+    description: "Install Flutter SDK & add bin folder to BASH_ENV"
+    parameters:
+      version:
+        type: string
+    steps:
+      - run:
+          name: "Install Flutter"
+          command: |
+            FL_PATH=$(bash <(curl -s https://raw.githubusercontent.com/brenodt/flutter_utilities/main/bin/flinstall) << parameters.version >>)
+            echo "export PATH=${FL_PATH}:${PATH}" >> $BASH_ENV
   install-flutter-deps:
     description: "Install Flutter dependencies"
     parameters:
@@ -490,46 +603,6 @@ commands:
           key: gem-cache-v2-{{ arch }}-{{ checksum "Gemfile.lock" }}
           paths:
             - vendor/bundle
-
-
-  # #  ---------------------------------------------
-  # #  (Flutter) Android-related commands
-  # #  ---------------------------------------------
-  install-flutter-linux:
-    description: "Installs the Linux flutter binary"
-    parameters:
-      version:
-        type: string
-    steps:
-      - run:
-          name: Install Flutter
-          command: |
-            cd && mkdir .flutter-sdk
-            cd .flutter-sdk
-            curl --fail --remote-time --silent --location -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_<< parameters.version >>-stable.tar.xz
-            tar xf flutter_linux_<< parameters.version >>-stable.tar.xz --strip-components=1
-            rm flutter_linux_<< parameters.version >>-stable.tar.xz
-            echo "export PATH=$PATH:`pwd`/bin" >> $BASH_ENV
-
-
-  # #  ---------------------------------------------
-  # #  (Flutter) iOS-related commands
-  # #  ---------------------------------------------
-  install-flutter-macos:
-    description: "Installs the MacOS flutter binary"
-    parameters:
-      version:
-        type: string
-    steps:
-      - run:
-          name: Install Flutter
-          command: |
-            cd && mkdir .flutter-sdk
-            cd .flutter-sdk
-            curl --fail --remote-time --silent --location -O https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_<< parameters.version >>-stable.zip
-            unzip flutter_macos_<< parameters.version >>-stable.zip
-            rm flutter_macos_<< parameters.version >>-stable.zip
-            echo "export PATH=$PATH:`pwd`/flutter/bin" >> $BASH_ENV
 
   install-cocoapods-deps:
     description: "Install Pods dependencies"
